Repository DescentDevelopers/Descent3, pull requests merged in 2024-05, with the labels that each got.

#260 Fix mercenary features
  Descent3/init.cpp
  Descent3/object_external.h
  Descent3/objinfo.cpp
  Descent3/objinfo.h
  Descent3/pilot.cpp
Labels: needs testing

#233 64 Bit-Safe Updates
  Descent3/audiotaunts.cpp
  Descent3/d3serial.cpp
  Descent3/d3serial.h
  Descent3/dedicated_server.cpp
  Descent3/multi.h
  Descent3/multi_external.h
  dd_lnxsound/ddlnxsound.h
  dd_sndlib/eax.h
  ddebug/lnxmono.cpp
  ddio_lnx/ddio_lnx.h
  ddio_lnx/lnxcdrom.cpp
  ddio_lnx/lnxio.cpp
  lib/Aencode.h
  lib/CZip.h
  lib/forcefeedback.h
  lib/linux/dyna_glide.h
  lib/mvelibw.h
  libacm/aencode.cpp
  libmve/SystemInterfaces.h
  libmve/lnxdsound.cpp
  libmve/lnxdsound.h
  libmve/mvelibl.cpp
  libmve/mvelibl.h
  lnxmvelib/lnxdraw.cpp
  lnxmvelib/lnxdsound.cpp
  lnxmvelib/lnxdsound.h
  lnxmvelib/mvelibi.h
  lnxmvelib/mvelibl.cpp
  lnxmvelib/mvelibl.h
  movie/d3movie.cpp
  netcon/includes/con_dll.h
  netcon/inetfile/Chttpget.cpp
  netcon/lanclient/lanclient.cpp
  netgames/dmfc/dmfcbase.cpp
  netgames/dmfc/dmfcfunctions.cpp
  netgames/dmfc/encryption.cpp
  netgames/includes/gamedll_header.h
  scripts/lnx/osiris_common.h
  scripts/osiris_common.h
Labels: needs testing, 64bit

#302 Generate "Direct TCP/IP.d3c" HOG file
  Descent3/CMakeLists.txt
  netcon/lanclient/CMakeLists.txt
  netcon/lanclient/TCP_IP.d3c.txt
  scripts/CMakeLists.txt
  tools/HogMaker/HogFormat.cpp
  tools/HogMaker/HogFormat.h
  tools/HogMaker/HogMaker.cpp
Labels: multiplayer

#341 Remove spdlog dependency, keep the logging module
  Brewfile
  CMakeLists.txt
  Descent3/lnxmain.cpp
  Descent3/winmain.cpp
  README.md
  lib/log.h
  misc/CMakeLists.txt
  misc/log.cpp
  vcpkg.json
Labels: build

#342 Remove DDAccess.h header, and associated DD_ACCESS_RING definition
  Descent3/intellivibe.cpp
  dd_grwin32/ddgrWin32DX.cpp
  dd_grwin32/ddgrWin32GDI.cpp
  dd_lnxsound/sdlsound.cpp
  dd_sndlib/Ds3dlib.cpp
  dd_vidwin32/video_win32.cpp
  ddio_lnx/lnxforcefeedback.cpp
  ddio_win/winforcefeedback.cpp
  ddio_win/winio.cpp
  ddio_win/winkey.cpp
  ddio_win/winmouse.cpp
  lib/DDAccess.h
  lib/Ddgr.h
  lib/TaskSystem.h
  lib/renderer.h
  lib/win/win32app.h
  linux/lnxcon.cpp
  linux/lnxcon_null.cpp
  linux/lnxcon_raw.cpp
  movie/d3movie.cpp
  renderer/HardwareOpenGL.cpp
  win32/wincon.cpp
  win32/wintask.cpp
Labels: cleanup

#316 replace md5 with custom implementation, with tests
  Descent3/LoadLevel.h
  Descent3/multi.cpp
  Descent3/multi_connect.cpp
  Descent3/multi_server.cpp
  md5/CMakeLists.txt
  md5/md5.cpp
  md5/md5.h
  md5/tests/CMakeLists.txt
  md5/tests/md5_tests.cpp
Labels: multiplayer

#301 Add missing licenses to CI artifacts and include licenses in all builds
  .github/workflows/build.yml
  Descent3/CMakeLists.txt
  third_party_licenses/libacm.txt
Labels: workflow

#349 Fix some more clang warnings
  Descent3/pilot.cpp
  netgames/dmfc/dmfcbase.cpp
  netgames/entropy/EntropyRoom.cpp
  netgames/includes/idmfc.h
  scripts/AIGame.cpp
  scripts/DallasFuncs.cpp
Labels: cleanup

#297 Revamp usage instructions
  CMakeLists.txt
  Descent3/CMakeLists.txt
  README.md
  netgames/CMakeLists.txt
Labels: documentation

#371 Only use standard mouse mode in debug
  Descent3/init.cpp
Labels: bugfix

#384 Update README.md
  README.md
Labels: documentation

#385 Update CMakePresets.json - Add Win64 preset
  .github/workflows/build.yml
  CMakePresets.json
Labels: workflow, build

#367 Reordering linux modules, cleanup code
  CMakeLists.txt
  Descent3/BriefingParse.h
  Descent3/CMakeLists.txt
  Descent3/credits.cpp
  Descent3/dedicated_server.cpp
  Descent3/lnxmain.cpp
  Descent3/menu.cpp
  Descent3/multi.h
  Descent3/newui.h
  cfile/cfile.cpp
  dd_sndlib/ddsoundload.cpp
  dd_video/CMakeLists.txt
  dd_video/ddvidlib.h
  dd_video/vidWin32FS.cpp
  dd_video/vidWin32Win.cpp
  dd_video/video_lnx.cpp
  dd_video/video_win32.cpp
  dd_vidwin32/CMakeLists.txt
  ddio_lnx/lnxfile.cpp
  ddvid_lnx/CMakeLists.txt
  lib/Controller.h
  lib/application.h
  lib/bitmap.h
  lib/lnxfix.h
  lib/lnxscreenmode.h
  lib/manage.h
  lib/networking.h
  lib/ui.h
  linux/CMakeLists.txt
  linux/linux_fix.h
  linux/lnxapp.cpp
  linux/lnxapp.h
  linux/lnxcontroller.cpp
  linux/lnxcontroller.h
  lnxcontroller/CMakeLists.txt
  manage/manage.cpp
  module/module.cpp
  netcon/includes/con_dll.h
  netcon/includes/inetgetfile.h
  renderer/HardwareOpenGL.cpp
  scripts/DallasFuncs.cpp
  scripts/linux_lib.cpp
  scripts/linux_lib.h
  scripts/osiris_import.h
  ui/UIEdit.cpp
Labels: cleanup

#318 Introducing installation steps
  .github/workflows/build.yml
  CMakeLists.txt
  Descent3/CMakeLists.txt
  netcon/lanclient/CMakeLists.txt
  netgames/anarchy/CMakeLists.txt
  netgames/coop/CMakeLists.txt
  netgames/ctf/CMakeLists.txt
  netgames/entropy/CMakeLists.txt
  netgames/hoard/CMakeLists.txt
  netgames/hyperanarchy/CMakeLists.txt
  netgames/monsterball/CMakeLists.txt
  netgames/roboanarchy/CMakeLists.txt
  netgames/tanarchy/CMakeLists.txt
  scripts/CMakeLists.txt
Labels: build

#374 Unify and cleanup sound related code into single sndlib module
  CMakeLists.txt
  Descent3/CMakeLists.txt
  Descent3/lnxmain.cpp
  Descent3/spew.h
  d3music/CMakeLists.txt
  dd_lnxsound/CMakeLists.txt
  dd_lnxsound/ddlnxsound.h
  dd_sndlib/CMakeLists.txt
  manage/CMakeLists.txt
  music/CMakeLists.txt
  music/music.h
  netgames/includes/gamedll_header.h
  physics/CMakeLists.txt
  sndlib/CMakeLists.txt
  sndlib/auddev.h
  sndlib/ddsndgeometry.h
  sndlib/ddsoundload.cpp
  sndlib/ds3dgeometry.cpp
  sndlib/ds3dlib.cpp
  sndlib/ds3dlib.h
  sndlib/ds3dlib_internal.h
  sndlib/dsound3d.cpp
  sndlib/eax.cpp
  sndlib/eax.h
  sndlib/eax2.h
  sndlib/hlsoundlib.cpp
  sndlib/hlsoundlib.h
  sndlib/mixer.cpp
  sndlib/mixer.h
  sndlib/sdlgeometry.cpp
  sndlib/sdlsound.cpp
  sndlib/sdlsound.h
  sndlib/sndrender.cpp
  sndlib/soundload.cpp
  sndlib/soundload.h
  sndlib/ssl_lib.cpp
  sndlib/ssl_lib.h
  sndlib/vmanpset.h
  stream_audio/CMakeLists.txt
  stream_audio/streamaudio.h
Labels: cleanup

#387 Fix RAND_MAX overflow warnings
  Descent3/AIGoal.cpp
  Descent3/AImain.cpp
  Descent3/ObjInit.cpp
  Descent3/Player.cpp
  Descent3/TelCom.cpp
  Descent3/WeaponFire.cpp
  Descent3/aipath.cpp
  Descent3/ambient.cpp
  Descent3/damage.cpp
  Descent3/fireball.cpp
  Descent3/matcen.cpp
  Descent3/osiris_predefs.cpp
  Descent3/procedurals.cpp
  Descent3/renderobject.cpp
  Descent3/robotfire.cpp
  Descent3/spew.cpp
  lib/psrand.h
  misc/psrand.cpp
  scripts/AIGame3.cpp
  vecmat/vector.cpp
Labels: cleanup
