Repository DescentDevelopers/Descent3, pull requests merged in 2024-04, with the labels that each got.

#50 Rename artifacts
  .github/workflows/build.yml
Labels: workflow

#45 Enable Linux CI build
  .github/workflows/build.yml
  CMakePresets.json
  Descent3/CMakeLists.txt
  scripts/hogutils/hogUtils-i686
Labels: workflow

#29 Mac CI fixes
  Brewfile
  CMakePresets.json
Labels: workflow

#18 Fix cf_SetSearchPath bad memory access (tested on macOS)
  cfile/CFILE.cpp
  lib/CFILE.H
Labels: needs testing

#150 Use new issue forms
  .github/ISSUE_TEMPLATE/01-build-failure.md
  .github/ISSUE_TEMPLATE/01-build-failure.yml
  .github/ISSUE_TEMPLATE/02-runtime-issue.md
  .github/ISSUE_TEMPLATE/02-runtime-issue.yml
  .github/ISSUE_TEMPLATE/03-wiki-issue.yml
Labels: workflow

#140 Object unlink sanity check
  Descent3/object.cpp
Labels: needs testing

#131 Fixed Release build
  CMakeLists.txt
  Descent3/render.cpp
  Descent3/winmain.cpp
  model/polymodel.cpp
Labels: needs testing

#158 Fix crash in hlsSystem::ComputePlayInfo(), #141
  Descent3/terrain.h
  sndlib/hlsoundlib.cpp
Labels: needs testing, 64bit
